# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
logbook:

recorder:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

fuelprices_dk:
  # Optional entries
  companies:
    # possible values are: circlek, f24, goon, ingo, oil, ok, q8 and shell
    - ok
    - shell
    - circlek
    - f24
    - goon
    - ingo
    - oil
    - q8
  fueltypes:
    # Possible values are: oktan 95, oktan 95+, oktan 100, diesel, diesel+
    #  - oktan 95
    - diesel

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

influxdb:
  host: !secret influx_db_host
  port: 8086
  database: !secret influx_db_database
  username: !secret influx_db_username
  password: !secret influx_db_password
  max_retries: 3
  default_measurement: state

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_vacuum_host
    token: !secret xiaomi_vacuum_token
    username: !secret xiaomi_cloud_username
    password: !secret xiaomi_cloud_password
    draw: ["all"]
    attributes:
      - calibration_points

notify:
  - platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret husum44@gmail.com

#-----------------------SENSORS ------------------------------------------
sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"

  - platform: history_stats
    name: W home time
    entity_id: person.william
    state: "home"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: history_stats
    name: G home time
    entity_id: person.gretha
    state: "home"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

  - platform: statistics
    entity_id: sensor.eloverblik_energy_total
    name: Eloverblik Monthly Statistics
    sampling_size: 50
    state_characteristic: mean
    max_age:
      days: 30

  - platform: statistics
    entity_id: sensor.eloverblik_energy_total
    name: Eloverblik Monthly Statistics
    sampling_size: 50
    state_characteristic: mean
    max_age:
      days: 30

  - platform: darksky
    api_key: !secret dark_sky_api_key
    forecast:
      - 0
    hourly_forecast:
      - 0
      - 1
      - 4
    language: da
    monitored_conditions:
      - summary
      - icon
      - temperature
      - apparent_temperature
      - precip_probability
    scan_interval:
      days: 0
      hours: 0
      minutes: 3
      seconds: 30

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
