# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
logbook:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.0.0/24

recorder:

frontend:
  themes: !include_dir_merge_named themes/

# Text to speech
tts:
  - platform: google_translate

influxdb:
  host: !secret influx_db_host
  port: 8086
  database: !secret influx_db_database
  username: !secret influx_db_username
  password: !secret influx_db_password
  max_retries: 3
  default_measurement: state

notify:
  - platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

panel_custom:
  - name: Automations
    sidebar_title: Automations
    sidebar_icon: mdi:cog-transfer
    js_url: /api/hassio/app/entrypoint.js
    url_path: config/automation/dashboard
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

#-----------------------SENSORS ------------------------------------------
sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"

  - platform: statistics
    entity_id: sensor.eloverblik_energy_total
    name: Eloverblik Monthly Statistics
    sampling_size: 50
    state_characteristic: mean
    max_age:
      days: 30

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: ipv4_address
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

  # - platform: imap_email_content
  #   server: imap.gmail.com
  #   port: 993
  #   username: !secret gmail_username
  #   password: !secret gmail_password
  #   senders:
  #     - !secret gmail_sender
  #     - !secret gmail_sender2
  #   name: Sidste tankning - kvittering
  #   value_template: >-
  #     {% if 'Kvittering for tankning af Diesel' in subject %}
  #       New data
  #     {% else %}
  #       No new receipt
  #     {% endif %}

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
